// <auto-generated />
using System;
using DCenter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCenter.Server.Migrations
{
    [DbContext(typeof(WeldReportContext))]
    [Migration("20260918064127_DCenter2")]
    partial class DCenter2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCenter.Server.Entities.BpvcMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrazingPNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GroupNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsoGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MinTensile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominalComposition")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("NominalThicknessLimits")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpecNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNoRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypicalProductForm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnsNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SpecNo", "PNo")
                        .IsUnique();

                    b.ToTable("DCenter_BpvcIx", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeatNumberLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatNumberRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointNumber")
                        .HasColumnType("int");

                    b.Property<string>("PartDescLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Rev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WpsNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("DCenter_Joints", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<string>("HeatLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointId")
                        .HasColumnType("int");

                    b.Property<string>("Manuf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JointId");

                    b.ToTable("DCenter_JointMaterials", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("DCenter_Lookups", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.MrnSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Form")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullSpecification")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNoRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Mrn")
                        .IsUnique();

                    b.ToTable("DCenter_MrnSpecs", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateWelded")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineerSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaInspector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReportRequired")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("DCenter_Reports", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.ReportStatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("DCenter_ReportStatusEvents", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Welder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("WelderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WelderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WelderName");

                    b.HasIndex("WelderNo");

                    b.ToTable("DCenter_Welders", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.WpsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseMetal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Process")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WpsNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PNo");

                    b.HasIndex("WpsNo");

                    b.HasIndex("WpsNo", "PNo")
                        .IsUnique();

                    b.ToTable("DCenter_WpsItems", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Report", "Report")
                        .WithMany("Joints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Joint", "Joint")
                        .WithMany("Materials")
                        .HasForeignKey("JointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joint");
                });

            modelBuilder.Entity("DCenter.Server.Entities.ReportStatusEvent", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Report", "Report")
                        .WithMany("StatusEvents")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Navigation("Joints");

                    b.Navigation("StatusEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
