// <auto-generated />
using System;
using DCenter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCenter.Server.Migrations
{
    [DbContext(typeof(WeldReportContext))]
    [Migration("20260923025000_DCenter_6")]
    partial class DCenter_6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCenter.Server.Entities.BpvcMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrazingPNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GroupNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsoGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MinTensile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominalComposition")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("NominalThicknessLimits")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpecNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNoRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypicalProductForm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnsNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SpecNo", "PNo");

                    b.ToTable("DCenter_BpvcIx", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Consumable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumableType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diameter")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MinStockKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableType", "Manufacturer", "Specification", "Diameter")
                        .IsUnique();

                    b.ToTable("DCenter_Consumables", null, t =>
                        {
                            t.HasCheckConstraint("CK_DCenter_Consumables_MinStock", "[MinStockKg] >= 0");

                            t.HasCheckConstraint("CK_DCenter_Consumables_Type", "[ConsumableType] IN (N'Bare & Powder Filler', N'Electrode Filler')");
                        });
                });

            modelBuilder.Entity("DCenter.Server.Entities.ConsumableLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId", "LotNumber")
                        .IsUnique();

                    b.ToTable("DCenter_ConsumableLots", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.ConsumableTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Requestor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("TxnDate")
                        .HasColumnType("date");

                    b.Property<string>("TxnType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("VoidsTxnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TxnDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TxnDate"), new[] { "TxnType", "QuantityKg", "IsVoided", "LotId", "Location" });

                    b.HasIndex("VoidsTxnId")
                        .IsUnique()
                        .HasFilter("[VoidsTxnId] IS NOT NULL");

                    b.HasIndex("LotId", "Location");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LotId", "Location"), new[] { "TxnType", "QuantityKg", "IsVoided" });

                    b.ToTable("DCenter_ConsumableTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_DCenter_ConsumableTxn_Location", "[Location] IN (N'Weldshop', N'Tool Crib')");

                            t.HasCheckConstraint("CK_DCenter_ConsumableTxn_Sign", "[QuantityKg] <> 0 AND ([TxnType] <> N'Receive' OR [QuantityKg] > 0) AND ([TxnType] <> N'Issue' OR [QuantityKg] < 0)");

                            t.HasCheckConstraint("CK_DCenter_ConsumableTxn_Type", "[TxnType] IN (N'Receive', N'Issue', N'Void')");

                            t.HasCheckConstraint("CK_DCenter_ConsumableTxn_Void", "([TxnType] = N'Void' AND [VoidsTxnId] IS NOT NULL) OR ([TxnType] <> N'Void' AND [VoidsTxnId] IS NULL)");
                        });
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeatNumberLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatNumberRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointNumber")
                        .HasColumnType("int");

                    b.Property<string>("PartDescLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Rev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WpsNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("DCenter_Joints", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<string>("HeatLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointId")
                        .HasColumnType("int");

                    b.Property<string>("Manuf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JointId");

                    b.ToTable("DCenter_JointMaterials", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("DCenter_Lookups", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.MrnSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Form")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullSpecification")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecNoRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Mrn");

                    b.ToTable("DCenter_MrnSpecs", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.ProcessTypeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Process", "Type")
                        .IsUnique();

                    b.ToTable("DCenter_ProcessTypeLinks", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateWelded")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineerSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaInspector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReportRequired")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("DCenter_Reports", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.ReportStatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("DCenter_ReportStatusEvents", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Welder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("WelderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WelderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WelderName");

                    b.HasIndex("WelderNo");

                    b.ToTable("DCenter_Welders", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.WpsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseMetal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Process")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WpsNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PNo");

                    b.HasIndex("WpsNo");

                    b.HasIndex("WpsNo", "PNo")
                        .IsUnique();

                    b.ToTable("DCenter_WpsItems", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.ConsumableLot", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Consumable", "Consumable")
                        .WithMany("Lots")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("DCenter.Server.Entities.ConsumableTransaction", b =>
                {
                    b.HasOne("DCenter.Server.Entities.ConsumableLot", "Lot")
                        .WithMany("Transactions")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DCenter.Server.Entities.ConsumableTransaction", null)
                        .WithMany()
                        .HasForeignKey("VoidsTxnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Report", "Report")
                        .WithMany("Joints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Joint", "Joint")
                        .WithMany("Materials")
                        .HasForeignKey("JointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joint");
                });

            modelBuilder.Entity("DCenter.Server.Entities.ReportStatusEvent", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Report", "Report")
                        .WithMany("StatusEvents")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Consumable", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("DCenter.Server.Entities.ConsumableLot", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Navigation("Joints");

                    b.Navigation("StatusEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
