// <auto-generated />
using System;
using DCenter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCenter.Server.Migrations
{
    [DbContext(typeof(WeldReportContext))]
    partial class WeldReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeatNumberLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatNumberRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointNumber")
                        .HasColumnType("int");

                    b.Property<string>("PartDescLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNoRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Rev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WpsNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("joints", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<string>("HeatLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JointId")
                        .HasColumnType("int");

                    b.Property<string>("Manuf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JointId");

                    b.ToTable("joint_materials", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("lookups", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateWelded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineerSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialSpec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSpec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNumber3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaInspector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReportRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Welder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("WelderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WelderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WelderName");

                    b.HasIndex("WelderNo");

                    b.ToTable("welders", (string)null);
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Report", "Report")
                        .WithMany("Joints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DCenter.Server.Entities.JointMaterial", b =>
                {
                    b.HasOne("DCenter.Server.Entities.Joint", "Joint")
                        .WithMany("Materials")
                        .HasForeignKey("JointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joint");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Joint", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DCenter.Server.Entities.Report", b =>
                {
                    b.Navigation("Joints");
                });
#pragma warning restore 612, 618
        }
    }
}
